name: ECE374-B Fall 2024
url: https://ecealgo.com/fa24/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
    description: This is me!
  # - key: staff
  #   name: Staff
  # - key: postdoc
  #   name: Researchers
  - key: grad
    name: Graduate Teaching Assistants
    description: Something 2
  - key: ugrad
    name: Undergraduate Teaching Assistants
    description: Something 3
  - key: faculty-alum
    name: Content Creators
    description: Instructors who have created and contributed to the pool of 374 content.    
  - key: grad-alum
    name: Alumni graduate teaching assistants 
    description: Past graduate teaching assistants. Most have created/contributed to the notes and problems/solutions.   
  - key: ugrad-alum
    name: Alumni Undergraduate Teaching Assistants
    description: Many of our past CAs. Most have moved on to successful careers but their time grading and hosting office hours won't be forgotten. 
  # - key: ugrad-alum
  #   name: Past Undergraduate Students
  # - key: collab
  #   name: Collaborators
  # - key: alum
  #   name: Alumni

# Number of news stories on the front page.
front_page_news: 1

# Base pathname for links.
base: '/fa24'

# make pages for the colections
collections:
  lectures:
    output: true
  labs:
    output: true
  resources:
    output: true
  policies: 
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  # - title: People
  #   link: /people.html
  - title: Lectures and Labs
    link: /lectures.html    
  - title: Homeworks
    link: /homeworks.html
  - title: Exams
    link: /exams.html    
  - title: Policies
    link: /policies.html
  - title: Schedules
    link: /office_hours.html       

#Variable that sets if this is a archived version of the site or not
archived: false
